import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "the-new-css-reset/css/reset.css";
import Provider from "@/context/provider";
import Header from "@/components/global/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="min-h-full">
        <Provider>
          <Header />
          <main className="">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
